### ISSUE TITLE
I tried this plugins into Nutmeg version giving this error 

### ISSUE THREAD

**Issue by Parvinkumar999** [Dicey-Tech/dt-classroom-plugin#10]
Hi BbrSofiane,
I have tried this plugins with Nutmeg. I wanted to create classrooms for school children i am creating a free Edx platform without any payment gateway but facing this issue with this plugins. 
[[](https://www.screencast.com/t/RrX2yh03h)](https://www.screencast.com/t/RrX2yh03h)

Please i am waiting for a positive reply from your side how i can add this plugins into my solution.

**Comment by BbrSofiane** [comment]
Hi @Parvinkumar999,

This plugin is no longer maintained (I will update the description). This plugin relies on a Django IDA that we are using for our own Open edX instance. Its implementation is highly volatile and tailored for our needs so if you are looking for something stable this is probably not the right path.
